### ISSUE TITLE
bug - python test.py is not working

### ISSUE THREAD

**Issue by JackyWay** [linuxacademy/content-google-cloud-certified-professional-machine-learning-engineer#1]
Bugfix: I ran into the issue below. Could you please take a look? Thank you.

```
cloud_user_p_9cb00d2c@cloudshell:~/content-google-cloud-certified-professional-machine-learning-engineer/deploying-ml-model/test (deploying-an-320-a95dcd5d)$ python test.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud_user_p_9cb00d2c/content-google-cloud-certified-professional-machine-learning-engineer/deploying-ml-model/test/test.py", line 5, in <module>
    print(resp.json())
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JackyWay** [comment]
Cloud Run log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 95, in init_process
    super().init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/main.py", line 12, in <module>
    model = keras.models.load_model("nn.h5")
  File "/usr/local/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "/usr/local/lib/python3.9/site-packages/keras/src/legacy/saving/legacy_h5_format.py", line 155, in load_model_from_hdf5
    **saving_utils.compile_args_from_training_config(
  File "/usr/local/lib/python3.9/site-packages/keras/src/legacy/saving/saving_utils.py", line 143, in compile_args_from_training_config
    loss = _deserialize_nested_config(losses.deserialize, loss_config)
  File "/usr/local/lib/python3.9/site-packages/keras/src/legacy/saving/saving_utils.py", line 202, in _deserialize_nested_config
    return deserialize_fn(config)
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/__init__.py", line 144, in deserialize
    return serialization_lib.deserialize_keras_object(
  File "/usr/local/lib/python3.9/site-packages/keras/src/saving/serialization_lib.py", line 581, in deserialize_keras_object
    return deserialize_keras_object(
  File "/usr/local/lib/python3.9/site-packages/keras/src/saving/serialization_lib.py", line 718, in deserialize_keras_object
    instance = cls.from_config(inner_config)
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/losses.py", line 34, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/losses.py", line 967, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/losses.py", line 16, in __init__
    super().__init__(reduction=reduction, name=name)
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/loss.py", line 29, in __init__
    self.reduction = standardize_reduction(reduction)
  File "/usr/local/lib/python3.9/site-packages/keras/src/losses/loss.py", line 80, in standardize_reduction
    raise ValueError(
ValueError: Invalid value for argument `reduction`. Expected one of {'sum_over_batch_size', 'sum', None, 'none'}. Received: reduction=auto
```
